# Generated by Django 5.0.6 on 2024-06-28 08:49

import uuid

import django.contrib.postgres.functions
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_alter_media_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="events.source",
            ),
        ),
        migrations.AlterField(
            model_name="media",
            name="uuid",
            field=models.UUIDField(
                db_default=django.contrib.postgres.functions.RandomUUID(),
                default=uuid.uuid4,
                editable=False,
                unique=True,
            ),
        ),
    ]
