# Generated by Django 5.0.6 on 2024-07-02 13:58

import django.contrib.postgres.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="uuid",
            field=models.UUIDField(
                db_default=django.contrib.postgres.functions.RandomUUID(),
                db_index=True,
                editable=False,
                unique=True,
            ),
        ),
    ]
