# Generated by Django 5.0.6 on 2024-07-10 12:50

import django.db.models.expressions
import django.db.models.functions.text
import project.utils.db.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_user_options_alter_user_date_joined_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="nickname",
            field=models.GeneratedField(
                db_persist=True,
                expression=project.utils.db.functions.ConcatOp(
                    django.db.models.functions.text.Upper(
                        django.db.models.functions.text.Left("first_name", 1)
                    ),
                    django.db.models.functions.text.Lower(
                        django.db.models.functions.text.Right(
                            "first_name",
                            django.db.models.expressions.CombinedExpression(
                                django.db.models.functions.text.Length("first_name"),
                                "-",
                                models.Value(1),
                            ),
                        )
                    ),
                    models.Value(" "),
                    django.db.models.functions.text.Upper(
                        django.db.models.functions.text.Left("last_name", 1)
                    ),
                    models.Value("."),
                ),
                output_field=models.CharField(max_length=150),
                verbose_name="Nickname",
            ),
        ),
    ]
