# Generated by Django 5.0.6 on 2024-07-04 15:35

import django.contrib.gis.db.models.fields
import django.contrib.postgres.functions
import django.db.models.deletion
import django.db.models.functions.datetime
import django.views.generic.dates
from django.conf import settings
from django.db import migrations, models

import project.utils.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.functions.datetime.Now(),
                        db_index=True,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_default=django.db.models.functions.datetime.Now(),
                        db_index=True,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("min_zoom", models.PositiveSmallIntegerField(default=7)),
                ("max_zoom", models.PositiveSmallIntegerField(default=15)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.PolygonField(
                        srid=4326, verbose_name="Geometry"
                    ),
                ),
                (
                    "north_west",
                    models.GeneratedField(
                        db_persist=True,
                        expression=models.Func(
                            models.Func("geom", function="ST_XMIN"),
                            models.Func("geom", function="ST_YMAX"),
                            function="ST_MAKEPOINT",
                        ),
                        output_field=django.contrib.gis.db.models.fields.PointField(
                            srid=4326
                        ),
                    ),
                ),
                (
                    "south_east",
                    models.GeneratedField(
                        db_persist=True,
                        expression=models.Func(
                            models.Func("geom", function="ST_XMAX"),
                            models.Func("geom", function="ST_YMIN"),
                            function="ST_MAKEPOINT",
                        ),
                        output_field=django.contrib.gis.db.models.fields.PointField(
                            srid=4326
                        ),
                    ),
                ),
            ],
            options={
                "verbose_name": "Area",
                "verbose_name_plural": "Areas",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ObservationCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=255, unique=True)),
                ("depth", models.PositiveIntegerField()),
                ("numchild", models.PositiveIntegerField(default=0)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.functions.datetime.Now(),
                        db_index=True,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_default=django.db.models.functions.datetime.Now(),
                        db_index=True,
                    ),
                ),
                ("label", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "pictogram",
                    project.utils.db.fields.SVGFileField(
                        blank=True,
                        upload_to="observation_categories",
                        verbose_name="Pictogram",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "ordering": ["-numchild", "path"],
            },
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.functions.datetime.Now(),
                        db_index=True,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_default=django.db.models.functions.datetime.Now(),
                        db_index=True,
                    ),
                ),
                ("label", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Source",
                "verbose_name_plural": "Sources",
                "ordering": ["label"],
            },
        ),
        migrations.CreateModel(
            name="Observation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.functions.datetime.Now(),
                        db_index=True,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_default=django.db.models.functions.datetime.Now(),
                        db_index=True,
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_default=django.contrib.postgres.functions.RandomUUID(),
                        db_index=True,
                        editable=False,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, default="", max_length=250, verbose_name="Name"
                    ),
                ),
                ("comments", models.TextField()),
                (
                    "event_date",
                    models.DateField(
                        db_index=True, default=django.views.generic.dates.timezone_today
                    ),
                ),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        srid=4326, verbose_name="Location"
                    ),
                ),
                (
                    "observer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="observations.observationcategory",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="observations.source",
                    ),
                ),
            ],
            options={
                "verbose_name": "Observation",
                "verbose_name_plural": "Observations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Media",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.functions.datetime.Now(),
                        db_index=True,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_default=django.db.models.functions.datetime.Now(),
                        db_index=True,
                    ),
                ),
                ("media_file", models.FileField(upload_to="media")),
                (
                    "uuid",
                    models.UUIDField(
                        db_default=django.contrib.postgres.functions.RandomUUID(),
                        db_index=True,
                        editable=False,
                        unique=True,
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[("image", "Image"), ("video", "Video")],
                        db_index=True,
                        default="image",
                        max_length=10,
                    ),
                ),
                ("legend", models.CharField(blank=True, default="", max_length=100)),
                (
                    "observation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medias",
                        to="observations.observation",
                        verbose_name="Observation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Media",
                "verbose_name_plural": "Medias",
                "ordering": ["created_at"],
            },
        ),
    ]
