# Generated by Django 5.0.6 on 2024-07-03 15:04

import project.utils.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("observations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="observationsubtype",
            name="pictogram",
            field=project.utils.db.fields.SVGFileField(
                upload_to="observation_types", verbose_name="Pictogram"
            ),
        ),
        migrations.AlterField(
            model_name="observationtype",
            name="pictogram",
            field=project.utils.db.fields.SVGFileField(
                upload_to="observation_types", verbose_name="Pictogram"
            ),
        ),
    ]
