# Generated by Django 5.0.6 on 2024-07-08 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("observations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="observation",
            name="comments",
            field=models.TextField(blank=True, default=""),
        ),
    ]
