# Generated by Django 5.0.6 on 2024-07-10 12:47

import django.db.models.deletion
import django.views.generic.dates
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("observations", "0002_alter_observation_comments"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="area",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="area",
            name="max_zoom",
            field=models.PositiveSmallIntegerField(
                default=15, verbose_name="Max. zoom"
            ),
        ),
        migrations.AlterField(
            model_name="area",
            name="min_zoom",
            field=models.PositiveSmallIntegerField(default=7, verbose_name="Min. zoom"),
        ),
        migrations.AlterField(
            model_name="area",
            name="name",
            field=models.CharField(max_length=100, unique=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="media",
            name="legend",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Legend"
            ),
        ),
        migrations.AlterField(
            model_name="media",
            name="media_file",
            field=models.FileField(upload_to="media", verbose_name="File"),
        ),
        migrations.AlterField(
            model_name="media",
            name="media_type",
            field=models.CharField(
                choices=[("image", "Image"), ("video", "Video")],
                db_index=True,
                default="image",
                max_length=10,
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="observation",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="observations.observationcategory",
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="observation",
            name="comments",
            field=models.TextField(blank=True, default="", verbose_name="Comments"),
        ),
        migrations.AlterField(
            model_name="observation",
            name="event_date",
            field=models.DateField(
                db_index=True,
                default=django.views.generic.dates.timezone_today,
                verbose_name="Event date",
            ),
        ),
        migrations.AlterField(
            model_name="observation",
            name="observer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Observer",
            ),
        ),
        migrations.AlterField(
            model_name="observation",
            name="source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="observations.source",
                verbose_name="Source",
            ),
        ),
        migrations.AlterField(
            model_name="observationcategory",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="observationcategory",
            name="label",
            field=models.CharField(max_length=100, unique=True, verbose_name="Label"),
        ),
        migrations.AlterField(
            model_name="source",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="source",
            name="label",
            field=models.CharField(max_length=100, unique=True, verbose_name="Label"),
        ),
    ]
