# Generated by Django 5.0.6 on 2024-07-12 07:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("observations", "0004_alter_observation_observer"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="observationcategory",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
    ]
