name: Quality checks

on:
  pull_request:
  push:
    branches:
      - master
      - main
      - next

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DEBIAN_FRONTEND: noninteractive

jobs:
    flake8:
        name: Python Flake8 check
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: astral-sh/setup-uv@v5
              with:
                  version: "latest"
                  python-version: ./backend/.python-version
                  enable-cache: true
                  cache-suffix: "ruff"

            - name: Install ruff
              working-directory: ./backend
              run: |
                uv pip install ruff -c requirements-dev.txt

            - name: Lint check
              working-directory: ./backend
              run: |
                ruff check project

            - name: Format check
              working-directory: ./backend
              run: |
                ruff format --check project

    prettier:
        name: JS Prettier check
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version-file: ./front-end/.nvmrc
                  cache: 'npm'
                  cache-dependency-path: ./front-end/.nvmrc

            - name: Install node dependencies
              working-directory: ./front-end
              run: |
                npm ci --no-audit

            - name: Prettier check
              working-directory: ./front-end
              run: |
                npm run format:check

    type:
        name: JS Type check
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version-file: ./front-end/.nvmrc
                  cache: 'npm'
                  cache-dependency-path: ./front-end/.nvmrc

            - name: Install node dependencies
              working-directory: ./front-end
              run: |
                npm ci --no-audit

            - name: Type check
              working-directory: ./front-end
              run: |
                npm run type:check
